SELECT MONTH,
       SUM(BIRTHS) AS BIRTH,
       CASE WHEN SUM(BIRTHS) = (SELECT MAX(total_births) FROM (SELECT SUM(BIRTHS) AS total_births FROM BIRTHDAYMONTH GROUP BY MONTH)) THEN 'red' ELSE 'blue' END AS COLORS
FROM BIRTHDAYMONTH
GROUP BY MONTH
ORDER BY MONTH